### ISSUE TITLE
怎样在自己的数据集上设置num-samples

### ISSUE THREAD

**Issue by dsagsdfgfdh** [aassxun/SEMICON#1]
我看了您的代码，发现num-samples的设置与数据集中的类别数量无关，因此我想请问一下这个参数该怎么设置

**Comment by aassxun** [comment]
您好，num-samples的设置参照了该领域的第一篇文章ExchNet: A Unied Hashing Network for Large-Scale Fine-Grained Image Retrieval（ECCV 2020），每个数据集的num-samples都和该文一致。您也可以直接按readme中提供的5个样例设置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aassxun/SEMICON"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 中午11:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[aassxun/SEMICON] 怎样在自己的数据集上设置num-samples (Issue #1)





 
我看了您的代码，发现num-samples的设置与数据集中的类别数量无关，因此我想请问一下这个参数该怎么设置

**Comment by dsagsdfgfdh** [comment]
非常感谢您的帮助，我还想请教一下，我使用的是Cub2011，在测试时候出现下面错误：
Traceback (most recent call last):
  File "/home/hx/yndw/SEMICON/run.py", line 143, in <module>
    run()
  File "/home/hx/yndw/SEMICON/run.py", line 53, in run
    mAP = net_arch.train(query_dataloader, train_dataloader, retrieval_dataloader, code_length, args)
  File "/home/hx/yndw/SEMICON/baseline_train.py", line 85, in train
    query_code = generate_code(model, query_dataloader, code_length, args.device)
  File "/home/hx/yndw/SEMICON/baseline_train.py", line 160, in generate_code
    hash_code, _, _, _, _, _, _, _ = model(data, targets)
ValueError: too many values to unpack (expected 8)

这个错误是因为什么原因呢

**Comment by aassxun** [comment]
抱歉，这份代码当时用于调试，忘了把中间没有用到的无用变量删除了。
hash_code, _, _, _, _, _, _, _ = model(data, targets)&nbsp;修改为：
hash_code = model(data, targets)即可，您可以在baseline.py文件中看到相关的返回参数。相关代码已经修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aassxun/SEMICON"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aassxun/SEMICON] 怎样在自己的数据集上设置num-samples (Issue #1)





 
非常感谢您的帮助，我还想请教一下，我使用的是Cub2011，在测试时候出现下面错误：
 Traceback (most recent call last):
 File "/home/hx/yndw/SEMICON/run.py", line 143, in 
 run()
 File "/home/hx/yndw/SEMICON/run.py", line 53, in run
 mAP = net_arch.train(query_dataloader, train_dataloader, retrieval_dataloader, code_length, args)
 File "/home/hx/yndw/SEMICON/baseline_train.py", line 85, in train
 query_code = generate_code(model, query_dataloader, code_length, args.device)
 File "/home/hx/yndw/SEMICON/baseline_train.py", line 160, in generate_code
 hash_code, _, _, _, _, _, _, _ = model(data, targets)
 ValueError: too many values to unpack (expected 8)
 
这个错误是因为什么原因呢

**Comment by dsagsdfgfdh** [comment]
非常感谢您的帮助！
