### ISSUE TITLE
indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by BJFU-CS2012** [aassxun/SEMICON#2]
我在自己的机器上训练安装的pytorch是GPU版本的，提示这个错误，但是在云服务器上边却没问题，可能的原因有哪些？谢谢您~

 File "/home/LS/SEMICON-main/run.py", line 142, in <module>
    run()
  File "/home/LS/SEMICON-main/run.py", line 53, in run
    mAP = net_arch.train(query_dataloader, train_dataloader, retrieval_dataloader, code_length, args)
  File "/home/LS/SEMICON-main/baseline_train.py", line 70, in train
    cnn_loss, hash_loss, quan_loss = criterion(F, B, S[index, :], sample_index[index])
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by aassxun** [comment]
> 我在自己的机器上训练安装的pytorch是GPU版本的，提示这个错误，但是在云服务器上边却没问题，可能的原因有哪些？谢谢您~
> 
> File "/home/LS/SEMICON-main/run.py", line 142, in run() File "/home/LS/SEMICON-main/run.py", line 53, in run mAP = net_arch.train(query_dataloader, train_dataloader, retrieval_dataloader, code_length, args) File "/home/LS/SEMICON-main/baseline_train.py", line 70, in train cnn_loss, hash_loss, quan_loss = criterion(F, B, S[index, :], sample_index[index]) RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

您好，我在服务器上重新运行了一遍没有类似的报错，本地报错有可能会是环境的问题，参考：https://blog.csdn.net/Chemist_Dong/article/details/128012131

另外可以检查一下device是否为'cuda:0'，或全部替换为cpu是否报错，以及其他类似代码是否也会在本地报错。

这类报错一般来说是表明代码试图在不同的设备之间进行数据传输，chatgpt给出了包括以下几种其他可能原因（概率较小，您在服务器上也没有问题，我个人更倾向于上面的答案）：
1.Tensor存储位置不一致：这个错误通常发生在使用GPU进行计算的时候，如果一个Tensor存储在GPU上，而另一个Tensor存储在CPU上，那么在对这两个Tensor进行操作时就会出现这个错误。要解决这个问题，可以使用.to()函数将所有的Tensor都转移到同一个设备上
2.模型和数据不在同一个设备上：当使用GPU进行训练时，模型和数据需要在同一个设备上，否则会出现这个错误。要解决这个问题，可以使用.to()函数将模型和数据都转移到同一个设备上
3.使用了不支持的操作：有些操作不支持GPU计算，例如某些numpy函数，这些操作需要将数据转移到CPU上进行操作。要解决这个问题，可以使用.cpu()函数将数据转移到CPU上
4.数据类型不匹配：当使用GPU进行计算时，Tensor的数据类型必须是float32或float64，如果数据类型不匹配，就会出现这个错误。要解决这个问题，可以使用.float()函数将数据类型转换为float32

**Comment by BJFU-CS2012** [comment]
好的，谢谢您的回复，我测试下
