### ISSUE TITLE
关于预训练权重文件

### ISSUE THREAD

**Issue by heart1128** [aassxun/SEMICON#4]
你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。

**Comment by aassxun** [comment]
> 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。

请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）

**Comment by heart1128** [comment]
> > 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。
> 
> 请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）

您好，是CUB200-2011数据集。

**Comment by aassxun** [comment]
> > > 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。
> > 
> > 
> > 请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）
> 
> 您好，是CUB200-2011数据集。

您好，请提供一下邮箱，另麻烦您提供一下复现的log文件

**Comment by heart1128** [comment]
> > > > 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。
> > > 
> > > 
> > > 请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）
> > 
> > 
> > 您好，是CUB200-2011数据集。
> 
> 您好，请提供一下邮箱，另麻烦您提供一下复现的log文件

好的，1020273485@qq.com，log文件用邮箱发给您吗?

**Comment by aassxun** [comment]
> > > > > 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。
> > > > 
> > > > 
> > > > 请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）
> > > 
> > > 
> > > 您好，是CUB200-2011数据集。
> > 
> > 
> > 您好，请提供一下邮箱，另麻烦您提供一下复现的log文件
> 
> 好的，[1020273485@qq.com](mailto:1020273485@qq.com)，log文件用邮箱发给您吗?

麻烦log文件发送至shenyang_98@njust.edu.cn，稍后会将对应的权重文件发您

**Comment by heart1128** [comment]
> > > > > > 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。
> > > > > 
> > > > > 
> > > > > 请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）
> > > > 
> > > > 
> > > > 您好，是CUB200-2011数据集。
> > > 
> > > 
> > > 您好，请提供一下邮箱，另麻烦您提供一下复现的log文件
> > 
> > 
> > 好的，[1020273485@qq.com](mailto:1020273485@qq.com)，log文件用邮箱发给您吗?
> 
> 麻烦log文件发送至[shenyang_98@njust.edu.cn](mailto:shenyang_98@njust.edu.cn)，稍后会将对应的权重文件发您

您好，log已发送至您的邮箱，再次感谢您的工作！

**Comment by aassxun** [comment]
> > > > > > > 你好，感谢你们的工作，我在复现过程中出现了偏差很大的结果，是否能够提供预训练的权重文件供我学习，谢谢。
> > > > > > 
> > > > > > 
> > > > > > 请问是哪个数据集，log文件和注意点昨日已额外更新，请参考SEMICON_log文件夹（SEMICON++暂未放出）
> > > > > 
> > > > > 
> > > > > 您好，是CUB200-2011数据集。
> > > > 
> > > > 
> > > > 您好，请提供一下邮箱，另麻烦您提供一下复现的log文件
> > > 
> > > 
> > > 好的，[1020273485@qq.com](mailto:1020273485@qq.com)，log文件用邮箱发给您吗?
> > 
> > 
> > 麻烦log文件发送至[shenyang_98@njust.edu.cn](mailto:shenyang_98@njust.edu.cn)，稍后会将对应的权重文件发您
> 
> 您好，log已发送至您的邮箱，再次感谢您的工作！

您好，已发送。可能有问题的超参数也已标注，若仍然存在问题请继续与我联系，谢谢
